# Generated by Django 6.0.5 on 2026-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('area', models.CharField(max_length=100, verbose_name='Área de especialidad')),
                ('expertise', models.TextField(verbose_name='Expertise / Conocimiento especializado')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('antiguedad', models.IntegerField(verbose_name='Años de experiencia')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para consulta')),
            ],
            options={
                'verbose_name': 'Experto',
                'verbose_name_plural': 'Expertos',
            },
        ),
        migrations.CreateModel(
            name='LeccionAprendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('POS', 'Sistemas POS'), ('RED', 'Redes y Conectividad'), ('HW', 'Hardware y Mantenimiento'), ('SW', 'Software y Actualizaciones'), ('BD', 'Bases de Datos'), ('SEG', 'Seguridad Informática')], max_length=3, verbose_name='Categoría')),
                ('problema', models.TextField(verbose_name='Problema identificado')),
                ('causa', models.TextField(verbose_name='Causa del problema')),
                ('solucion', models.TextField(verbose_name='Solución aplicada')),
                ('resultado', models.TextField(verbose_name='Resultado obtenido')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Lección Aprendida',
                'verbose_name_plural': 'Lecciones Aprendidas',
            },
        ),
    ]
